# Generated by Django 5.0.4 on 2024-04-22 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='image',
        ),
    ]
