# Generated by Django 5.0.4 on 2024-04-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_services_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='image',
            new_name='image_in',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='category',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='client',
            field=models.CharField(default='Default Name', max_length=255),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='date',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='image_out',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/'),
        ),
    ]
